"""Project generator — renders runnable projects from templates."""

from __future__ import annotations

import shutil
from pathlib import Path

from jinja2 import Environment, FileSystemLoader

from rag_builder.config import ProjectConfig


class ProjectGenerator:
    """Generate a runnable RAG project from config + templates."""

    def __init__(self, config: ProjectConfig):
        self.config = config
        self.template_dir = Path(__file__).parent.parent / "templates"

    def generate(self) -> Path:
        """Generate the full project. Returns output directory path."""
        output = Path(self.config.output_dir) / self.config.project_name
        output.mkdir(parents=True, exist_ok=True)

        # Choose template
        template_name = "advanced" if self.config.with_agent else "basic"

        # Render template files
        env = Environment(
            loader=FileSystemLoader(str(self.template_dir)),
            keep_trailing_newline=True,
        )

        template_vars = {
            "project_name": self.config.project_name,
            "config": self.config,
            "llm_provider": self.config.llm.provider.value,
            "llm_model": self.config.llm.model,
            "llm_base_url": self.config.llm.base_url or "",
            "embedder_provider": self.config.embedder.provider.value,
            "embedder_model": self.config.embedder.model,
            "vectorstore_type": self.config.vectorstore.store_type.value,
            "with_agent": self.config.with_agent,
            "with_frontend": self.config.with_frontend,
        }

        # Render each template file
        template_path = self.template_dir / template_name
        if template_path.exists():
            self._render_directory(env, template_path, output, template_vars)

        # Generate config file
        self._generate_config(output)

        # Generate requirements.txt
        self._generate_requirements(output)

        return output

    def _render_directory(
        self, env: Environment, src: Path, dst: Path, variables: dict
    ) -> None:
        """Recursively render template directory."""
        for item in src.iterdir():
            if item.is_dir():
                new_dst = dst / item.name
                new_dst.mkdir(exist_ok=True)
                self._render_directory(env, item, new_dst, variables)
            elif item.suffix == ".j2":
                # Render Jinja2 template — path relative to template root
                rel_path = item.relative_to(self.template_dir)
                template = env.get_template(str(rel_path))
                content = template.render(**variables)
                out_file = dst / item.stem  # Remove .j2 extension
                out_file.write_text(content)
            else:
                # Copy as-is
                shutil.copy2(item, dst / item.name)

    def _generate_config(self, output: Path) -> None:
        """Generate .env file with configuration."""
        env_content = f"""# RAG Project Configuration
# Generated by rag-builder

# LLM
LLM_PROVIDER={self.config.llm.provider.value}
LLM_MODEL={self.config.llm.model}
LLM_BASE_URL={self.config.llm.base_url or ""}
LLM_API_KEY={self.config.llm.api_key or "your-api-key-here"}

# Embeddings
EMBEDDER_PROVIDER={self.config.embedder.provider.value}
EMBEDDER_MODEL={self.config.embedder.model}
EMBEDDER_API_KEY={self.config.embedder.api_key or "your-api-key-here"}

# Vector Store
VECTORSTORE_TYPE={self.config.vectorstore.store_type.value}
VECTORSTORE_DIR=./vectorstore

# Retrieval
TOP_K={self.config.retriever.top_k}
USE_RERANKER={str(self.config.retriever.use_reranker).lower()}

# Chunking
CHUNK_SIZE={self.config.chunk.chunk_size}
CHUNK_OVERLAP={self.config.chunk.chunk_overlap}
"""
        (output / ".env").write_text(env_content)

    def _generate_requirements(self, output: Path) -> None:
        """Generate requirements.txt."""
        deps = [
            "openai>=1.0",
            "chromadb>=0.4",
            "pypdf>=3.0",
            "python-docx>=0.8.11",
            "markdown>=3.5",
            "beautifulsoup4>=4.12",
            "tiktoken>=0.5",
            "chardet>=5.0",
            "python-dotenv>=1.0",
            "pydantic>=2.0",
        ]
        if self.config.with_frontend:
            deps.append("streamlit>=1.28")

        (output / "requirements.txt").write_text("\n".join(deps) + "\n")
